# Configurazione di Rete del Server
server.host=localhost
server.tcp.port=8888
server.udp.port=8889

# Percorsi di Persistenza
persistence.users.path=data/users.json
persistence.games.path=data/games.json
game.words.path=data/words.json

# Intervalli Temporali (in minuti)
persistence.flush.interval.minutes=5
game.duration.minutes=1